services:
  app:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Use all available GPUs
      - API_KEY=${API_KEY:-your_api_key_here}
      - PORT=9090  # Ensure port alignment
      - DEFAULT_VOICE=${DEFAULT_VOICE:-Emilia_ZH_EN}
      - REQUIRE_API_KEY=${REQUIRE_API_KEY:-True}
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}  # Specify GPU driver
              count: 1  # Use 1 GPU; change to 'all' if multiple are needed
              capabilities: [gpu]
    ports:
      - '9090:9090'
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./ckpts:/app/ckpts
    command: /bin/sh -c "python3 /app/test.py && python3 /app/server.py"
